#dev env

#API testing
clientId = haha
clientSecret = heheh
domain = de

default.annotation.engine.version = 1.6.2.0

datasource.url=jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
datasource.username=test
datasource.password=123


